### ISSUE TITLE
Update swow-stub to 1.5.2

### ISSUE THREAD

**Issue by moroswitie** [swow/swow-stub#1]
When developing a package that requires swow, it would be nice to include this package.

Could you please update this package to the latest version (currently 1.5.2) and add a tag.
This would allow us to install it using composer

**Comment by moroswitie** [comment]
After analyzing I realized this package is replaced.
Closing ticket

**Comment by moroswitie** [comment]
After analyzing I released this package is replaced.

**Comment by twose** [comment]
Updated.
